name: Feature request
description: Suggest an improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are you facing?
      placeholder: Describe the pain point.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: Describe your proposal.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives you evaluated?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, examples, references.
